// <auto-generated />
using JayAPI.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using System;

namespace JayAPI.Migrations
{
    [DbContext(typeof(JayContexto))]
    partial class JayContextoModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("MySql:ValueGenerationStrategy", MySqlValueGenerationStrategy.IdentityColumn)
                .HasAnnotation("ProductVersion", "2.0.3-rtm-10026");

            modelBuilder.Entity("JayAPI.Models.Cliente", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("cnpj")
                        .HasMaxLength(17);

                    b.Property<int?>("enderecoCobrancaid");

                    b.Property<int?>("enderecoEntregaid");

                    b.Property<int?>("enderecoid");

                    b.Property<string>("ie")
                        .HasMaxLength(20);

                    b.Property<string>("nomeFantasia")
                        .HasMaxLength(200);

                    b.Property<bool>("pessoaJuridica");

                    b.Property<string>("razaoSocial")
                        .HasMaxLength(200);

                    b.HasKey("id");

                    b.HasIndex("enderecoCobrancaid");

                    b.HasIndex("enderecoEntregaid");

                    b.HasIndex("enderecoid");

                    b.ToTable("Clientes");
                });

            modelBuilder.Entity("JayAPI.Models.Endereco", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("bairro")
                        .HasMaxLength(200);

                    b.Property<string>("cep")
                        .HasMaxLength(9);

                    b.Property<string>("cidade")
                        .HasMaxLength(200);

                    b.Property<string>("complemento")
                        .HasMaxLength(100);

                    b.Property<string>("endereco")
                        .HasMaxLength(200);

                    b.Property<string>("numero")
                        .HasMaxLength(10);

                    b.Property<string>("uf")
                        .HasMaxLength(2);

                    b.HasKey("id");

                    b.ToTable("Endereco");
                });

            modelBuilder.Entity("JayAPI.Models.Fornecedor", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("cnpj")
                        .HasMaxLength(17);

                    b.Property<int?>("enderecoCobrancaid");

                    b.Property<int?>("enderecoEntregaid");

                    b.Property<int?>("enderecoid");

                    b.Property<string>("ie")
                        .HasMaxLength(20);

                    b.Property<string>("nomeFantasia")
                        .HasMaxLength(200);

                    b.Property<bool>("pessoaJuridica");

                    b.Property<string>("razaoSocial")
                        .HasMaxLength(200);

                    b.HasKey("id");

                    b.HasIndex("enderecoCobrancaid");

                    b.HasIndex("enderecoEntregaid");

                    b.HasIndex("enderecoid");

                    b.ToTable("Fornecedores");
                });

            modelBuilder.Entity("JayAPI.Models.Cliente", b =>
                {
                    b.HasOne("JayAPI.Models.Endereco", "enderecoCobranca")
                        .WithMany()
                        .HasForeignKey("enderecoCobrancaid");

                    b.HasOne("JayAPI.Models.Endereco", "enderecoEntrega")
                        .WithMany()
                        .HasForeignKey("enderecoEntregaid");

                    b.HasOne("JayAPI.Models.Endereco", "endereco")
                        .WithMany()
                        .HasForeignKey("enderecoid");
                });

            modelBuilder.Entity("JayAPI.Models.Fornecedor", b =>
                {
                    b.HasOne("JayAPI.Models.Endereco", "enderecoCobranca")
                        .WithMany()
                        .HasForeignKey("enderecoCobrancaid");

                    b.HasOne("JayAPI.Models.Endereco", "enderecoEntrega")
                        .WithMany()
                        .HasForeignKey("enderecoEntregaid");

                    b.HasOne("JayAPI.Models.Endereco", "endereco")
                        .WithMany()
                        .HasForeignKey("enderecoid");
                });
#pragma warning restore 612, 618
        }
    }
}
